version: '3.8'



services:
  app:
    image: nvidia/cuda:12.2.0-devel-ubuntu20.04
    container_name: cuda-python-3.10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app

    ports:
      - "8089:22"  # 映射主機和容器的 8089 埠
    command: >
            bash -c "export DEBIAN_FRONTEND=noninteractive &&
            apt-get update &&
            apt-get install -y curl gnupg2 openssh-server openssh-client lsb-release &&
            echo 'deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main' > /etc/apt/sources.list.d/deadsnakes-ppa.list &&
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6A755776 &&  
            apt-get update &&
            apt-get install -y python3.10 python3.10-distutils build-essential python3.10-dev &&
            curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 &&
            ln -sf python3.10 /usr/bin/python3 &&
            mkdir -p /var/run/sshd /etc/ssh &&
            useradd -m III &&
            echo 'III:III123' | chpasswd &&
            ssh-keygen -A &&
            echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
            echo 'AllowUsers III' >> /etc/ssh/sshd_config &&
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 &&
            pip install transformers trl datasets peft bitsandbytes accelerate wandb tensorboardX &&
            /usr/sbin/sshd -D"





           



    tty: true  # 允許容器保持運行，直到手動終止